### ISSUE TITLE
Summary.md imcomplete markdown tag

### ISSUE THREAD

**Issue by Hashfyre** [gocd/developer.go.cd#68]
```
  * [Common](4/4.4.md)
      * [Plugin Architecture](4/4.4.1.md)
      * [Agent - Server Communication](
```
at `line 60`

**Comment by Hashfyre** [comment]
Published rendering.
<img width="301" alt="screen shot 2018-12-03 at 1 39 12 pm" src="https://user-images.githubusercontent.com/581287/49361034-e3e07980-f700-11e8-89e3-24dcfe6e21b2.png">

The link for `Agent - Server Communication` goes missing because of this. Let me know if I can make a PR to fix this.

`[Agent - Server Communication](4/4.4.1.md)` should fix this right?

**Comment by ketan** [comment]
> Let me know if I can make a PR to fix this.

Yes, please :)

**Comment by chadlwilson** [comment]
This documentation seems to be elsewhere now, just cleaning up old issues.
